# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dominik/Documents/Yggdrasil

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dominik/Documents/Yggdrasil

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dominik/Documents/Yggdrasil/CMakeFiles /home/dominik/Documents/Yggdrasil/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dominik/Documents/Yggdrasil/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Yggdrasil

# Build rule for target.
Yggdrasil: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Yggdrasil
.PHONY : Yggdrasil

# fast build rule for target.
Yggdrasil/fast:
	$(MAKE) -f CMakeFiles/Yggdrasil.dir/build.make CMakeFiles/Yggdrasil.dir/build
.PHONY : Yggdrasil/fast

src/AudioDataflow.o: src/AudioDataflow.cpp.o

.PHONY : src/AudioDataflow.o

# target to build an object file
src/AudioDataflow.cpp.o:
	$(MAKE) -f CMakeFiles/Yggdrasil.dir/build.make CMakeFiles/Yggdrasil.dir/src/AudioDataflow.cpp.o
.PHONY : src/AudioDataflow.cpp.o

src/AudioDataflow.i: src/AudioDataflow.cpp.i

.PHONY : src/AudioDataflow.i

# target to preprocess a source file
src/AudioDataflow.cpp.i:
	$(MAKE) -f CMakeFiles/Yggdrasil.dir/build.make CMakeFiles/Yggdrasil.dir/src/AudioDataflow.cpp.i
.PHONY : src/AudioDataflow.cpp.i

src/AudioDataflow.s: src/AudioDataflow.cpp.s

.PHONY : src/AudioDataflow.s

# target to generate assembly for a file
src/AudioDataflow.cpp.s:
	$(MAKE) -f CMakeFiles/Yggdrasil.dir/build.make CMakeFiles/Yggdrasil.dir/src/AudioDataflow.cpp.s
.PHONY : src/AudioDataflow.cpp.s

src/AudioObject.o: src/AudioObject.cpp.o

.PHONY : src/AudioObject.o

# target to build an object file
src/AudioObject.cpp.o:
	$(MAKE) -f CMakeFiles/Yggdrasil.dir/build.make CMakeFiles/Yggdrasil.dir/src/AudioObject.cpp.o
.PHONY : src/AudioObject.cpp.o

src/AudioObject.i: src/AudioObject.cpp.i

.PHONY : src/AudioObject.i

# target to preprocess a source file
src/AudioObject.cpp.i:
	$(MAKE) -f CMakeFiles/Yggdrasil.dir/build.make CMakeFiles/Yggdrasil.dir/src/AudioObject.cpp.i
.PHONY : src/AudioObject.cpp.i

src/AudioObject.s: src/AudioObject.cpp.s

.PHONY : src/AudioObject.s

# target to generate assembly for a file
src/AudioObject.cpp.s:
	$(MAKE) -f CMakeFiles/Yggdrasil.dir/build.make CMakeFiles/Yggdrasil.dir/src/AudioObject.cpp.s
.PHONY : src/AudioObject.cpp.s

src/Objects.o: src/Objects.cpp.o

.PHONY : src/Objects.o

# target to build an object file
src/Objects.cpp.o:
	$(MAKE) -f CMakeFiles/Yggdrasil.dir/build.make CMakeFiles/Yggdrasil.dir/src/Objects.cpp.o
.PHONY : src/Objects.cpp.o

src/Objects.i: src/Objects.cpp.i

.PHONY : src/Objects.i

# target to preprocess a source file
src/Objects.cpp.i:
	$(MAKE) -f CMakeFiles/Yggdrasil.dir/build.make CMakeFiles/Yggdrasil.dir/src/Objects.cpp.i
.PHONY : src/Objects.cpp.i

src/Objects.s: src/Objects.cpp.s

.PHONY : src/Objects.s

# target to generate assembly for a file
src/Objects.cpp.s:
	$(MAKE) -f CMakeFiles/Yggdrasil.dir/build.make CMakeFiles/Yggdrasil.dir/src/Objects.cpp.s
.PHONY : src/Objects.cpp.s

src/Patch.o: src/Patch.cpp.o

.PHONY : src/Patch.o

# target to build an object file
src/Patch.cpp.o:
	$(MAKE) -f CMakeFiles/Yggdrasil.dir/build.make CMakeFiles/Yggdrasil.dir/src/Patch.cpp.o
.PHONY : src/Patch.cpp.o

src/Patch.i: src/Patch.cpp.i

.PHONY : src/Patch.i

# target to preprocess a source file
src/Patch.cpp.i:
	$(MAKE) -f CMakeFiles/Yggdrasil.dir/build.make CMakeFiles/Yggdrasil.dir/src/Patch.cpp.i
.PHONY : src/Patch.cpp.i

src/Patch.s: src/Patch.cpp.s

.PHONY : src/Patch.s

# target to generate assembly for a file
src/Patch.cpp.s:
	$(MAKE) -f CMakeFiles/Yggdrasil.dir/build.make CMakeFiles/Yggdrasil.dir/src/Patch.cpp.s
.PHONY : src/Patch.cpp.s

src/StringFormat.o: src/StringFormat.cpp.o

.PHONY : src/StringFormat.o

# target to build an object file
src/StringFormat.cpp.o:
	$(MAKE) -f CMakeFiles/Yggdrasil.dir/build.make CMakeFiles/Yggdrasil.dir/src/StringFormat.cpp.o
.PHONY : src/StringFormat.cpp.o

src/StringFormat.i: src/StringFormat.cpp.i

.PHONY : src/StringFormat.i

# target to preprocess a source file
src/StringFormat.cpp.i:
	$(MAKE) -f CMakeFiles/Yggdrasil.dir/build.make CMakeFiles/Yggdrasil.dir/src/StringFormat.cpp.i
.PHONY : src/StringFormat.cpp.i

src/StringFormat.s: src/StringFormat.cpp.s

.PHONY : src/StringFormat.s

# target to generate assembly for a file
src/StringFormat.cpp.s:
	$(MAKE) -f CMakeFiles/Yggdrasil.dir/build.make CMakeFiles/Yggdrasil.dir/src/StringFormat.cpp.s
.PHONY : src/StringFormat.cpp.s

src/Yggdrasil.o: src/Yggdrasil.cpp.o

.PHONY : src/Yggdrasil.o

# target to build an object file
src/Yggdrasil.cpp.o:
	$(MAKE) -f CMakeFiles/Yggdrasil.dir/build.make CMakeFiles/Yggdrasil.dir/src/Yggdrasil.cpp.o
.PHONY : src/Yggdrasil.cpp.o

src/Yggdrasil.i: src/Yggdrasil.cpp.i

.PHONY : src/Yggdrasil.i

# target to preprocess a source file
src/Yggdrasil.cpp.i:
	$(MAKE) -f CMakeFiles/Yggdrasil.dir/build.make CMakeFiles/Yggdrasil.dir/src/Yggdrasil.cpp.i
.PHONY : src/Yggdrasil.cpp.i

src/Yggdrasil.s: src/Yggdrasil.cpp.s

.PHONY : src/Yggdrasil.s

# target to generate assembly for a file
src/Yggdrasil.cpp.s:
	$(MAKE) -f CMakeFiles/Yggdrasil.dir/build.make CMakeFiles/Yggdrasil.dir/src/Yggdrasil.cpp.s
.PHONY : src/Yggdrasil.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Yggdrasil"
	@echo "... edit_cache"
	@echo "... src/AudioDataflow.o"
	@echo "... src/AudioDataflow.i"
	@echo "... src/AudioDataflow.s"
	@echo "... src/AudioObject.o"
	@echo "... src/AudioObject.i"
	@echo "... src/AudioObject.s"
	@echo "... src/Objects.o"
	@echo "... src/Objects.i"
	@echo "... src/Objects.s"
	@echo "... src/Patch.o"
	@echo "... src/Patch.i"
	@echo "... src/Patch.s"
	@echo "... src/StringFormat.o"
	@echo "... src/StringFormat.i"
	@echo "... src/StringFormat.s"
	@echo "... src/Yggdrasil.o"
	@echo "... src/Yggdrasil.i"
	@echo "... src/Yggdrasil.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

